import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarDays, GripVertical, Pencil, Plus, Save, Trash2, UserMinus, UserPlus, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { releaseApi } from "../api/releases";
import { ProgressBar } from "../components/ProgressBar";
import { StatusBadge } from "../components/StatusBadge";
import { Toasts } from "../components/Toast";
import { useAuth } from "../contexts/AuthContext";
import { useRealtime } from "../hooks/useRealtime";
import { useToast } from "../hooks/useToast";
import type { CollaboratorInput, Release } from "../types";

const activityCopy: Record<string, string> = {
  release_created: "created the release", release_updated: "updated the release",
  checklist_completed: "completed", checklist_unchecked: "unchecked", step_deleted: "deleted step",
  notes_updated: "updated release notes", collaborator_added: "added a teammate",
  collaborator_removed: "removed a teammate", collaborator_role_updated: "updated a teammate role",
};

export function ReleaseDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const releaseId = Number(id); const queryClient = useQueryClient(); useRealtime();
  const { user } = useAuth();
  const { messages, notify } = useToast(); const [info, setInfo] = useState(""); const [editing, setEditing] = useState(false); const [dragged, setDragged] = useState<number | null>(null);
  const [collaboratorEmail, setCollaboratorEmail] = useState(""); const [collaboratorRole, setCollaboratorRole] = useState<CollaboratorInput["role"]>("other");
  const [editingRelease, setEditingRelease] = useState(false); const [releaseName, setReleaseName] = useState(""); const [releaseDueDate, setReleaseDueDate] = useState("");
  const releaseQuery = useQuery({ queryKey: ["release", releaseId], queryFn: () => releaseApi.get(releaseId), enabled: Number.isInteger(releaseId) });
  const activitiesQuery = useQuery({ queryKey: ["activities", releaseId], queryFn: () => releaseApi.activities(releaseId), enabled: !!releaseQuery.data });
  const release = releaseQuery.data;
  const collaborators = release?.collaborators ?? [];
  useEffect(() => { if (release) { setInfo(release.additional_info ?? ""); setReleaseName(release.name); setReleaseDueDate(release.due_date); } }, [release]);
  const canDelete = release?.access_role === "owner";
  const canEditRelease = release?.access_role === "owner" || release?.access_role === "admin";
  const canManageCollaborators = canEditRelease;
  const checklistMutation = useMutation({
    mutationFn: (steps: Record<string, boolean>) => releaseApi.updateChecklist(releaseId, steps),
    onMutate: async (steps) => {
      await queryClient.cancelQueries({ queryKey: ["release", releaseId] });
      const previous = queryClient.getQueryData<Release>(["release", releaseId]);
      if (previous) { const completed = Object.values(steps).filter(Boolean).length; queryClient.setQueryData<Release>(["release", releaseId], { ...previous, steps, completed_steps: completed, total_steps: Object.keys(steps).length, status: completed === 0 ? "planned" : completed === Object.keys(steps).length ? "done" : "ongoing" }); }
      return { previous };
    },
    onError: (_error, _steps, context) => { if (context?.previous) queryClient.setQueryData(["release", releaseId], context.previous); notify("Update failed — your change was restored", "error"); },
    onSuccess: (updated) => { queryClient.setQueryData(["release", releaseId], updated); void queryClient.invalidateQueries({ queryKey: ["activities", releaseId] }); },
  });
  const updateSteps = (steps: Record<string, boolean>) => checklistMutation.mutate(steps);
  const rename = (oldName: string, newName: string) => { if (!release || !newName.trim() || newName === oldName || (newName in release.steps)) return; const next: Record<string, boolean> = {}; Object.entries(release.steps).forEach(([name, done]) => { next[name === oldName ? newName.trim() : name] = done; }); updateSteps(next); };
  const removeStep = (name: string) => { if (!release || Object.keys(release.steps).length === 1) return; const next = { ...release.steps }; delete next[name]; updateSteps(next); };
  const addStep = () => { if (!release) return; let number = Object.keys(release.steps).length + 1; while (`New Step ${number}` in release.steps) number += 1; updateSteps({ ...release.steps, [`New Step ${number}`]: false }); };
  const drop = (target: number) => { if (!release || dragged === null || dragged === target) return; const entries = Object.entries(release.steps); const [entry] = entries.splice(dragged, 1); entries.splice(target, 0, entry); setDragged(null); updateSteps(Object.fromEntries(entries)); };
  const saveInfo = async () => { if (!release) return; try { const updated = await releaseApi.updateInfo(release.id, info.trim() || null); queryClient.setQueryData(["release", releaseId], updated); void queryClient.invalidateQueries({ queryKey: ["activities", releaseId] }); notify("Additional information saved"); } catch { notify("Couldn’t save information", "error"); } };
  const saveRelease = async () => { if (!release || !releaseName.trim() || !releaseDueDate) return; try { const updated = await releaseApi.update(release.id, { name: releaseName.trim(), due_date: releaseDueDate, additional_info: release.additional_info }); queryClient.setQueryData(["release", releaseId], updated); setEditingRelease(false); notify("Release updated"); } catch { notify("Couldn’t update release", "error"); } };
  const addCollaborator = async () => { if (!release || !collaboratorEmail.trim()) return; try { const updated = await releaseApi.addCollaborator(release.id, { email: collaboratorEmail.trim().toLowerCase(), role: collaboratorRole }); queryClient.setQueryData(["release", releaseId], updated); setCollaboratorEmail(""); void queryClient.invalidateQueries({ queryKey: ["activities", releaseId] }); notify("Teammate added to this release"); } catch (error: unknown) { notify((error as { response?: { data?: { detail?: string } } }).response?.data?.detail ?? "Couldn’t add teammate", "error"); } };
  const updateCollaborator = async (userId: string, role: CollaboratorInput["role"]) => { if (!release) return; try { const updated = await releaseApi.updateCollaborator(release.id, userId, role); queryClient.setQueryData(["release", releaseId], updated); notify("Teammate role updated"); } catch { notify("Couldn’t update teammate", "error"); } };
  const removeCollaborator = async (userId: string) => { if (!release || !window.confirm("Remove this teammate from the release?")) return; try { const updated = await releaseApi.removeCollaborator(release.id, userId); queryClient.setQueryData(["release", releaseId], updated); notify("Teammate removed"); } catch { notify("Couldn’t remove teammate", "error"); } };
  const remove = async () => { if (!release || !window.confirm(`Delete “${release.name}”? This cannot be undone.`)) return; try { await releaseApi.delete(release.id); navigate("/"); } catch { notify("You do not have permission to delete this release", "error"); } };
  if (releaseQuery.isLoading) return <div className="mx-auto max-w-5xl p-6"><div className="h-96 animate-pulse rounded-2xl bg-white dark:bg-slate-900" /></div>;
  if (releaseQuery.isError || !release) return <div className="state mx-auto mt-16 max-w-xl"><h2>Release unavailable</h2><p>This release does not exist or you do not have access.</p><Link className="btn-primary mt-4" to="/">Back to releases</Link></div>;
  return <><Toasts messages={messages} /><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Link to="/" className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-brand"><ArrowLeft size={18} />All releases</Link>
    <section className="rounded-2xl bg-ink p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex-1"><div className="flex items-center gap-2"><StatusBadge status={release.status} /><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold capitalize">{release.access_role}</span></div>{editingRelease ? <div className="mt-4 grid max-w-xl gap-3 sm:grid-cols-[1fr_180px]"><input aria-label="Edit release name" value={releaseName} onChange={(event) => setReleaseName(event.target.value)} className="rounded-lg border border-white/20 bg-white/10 px-3 py-2 font-bold text-white" /><input aria-label="Edit due date" type="date" value={releaseDueDate} onChange={(event) => setReleaseDueDate(event.target.value)} className="rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-white [color-scheme:dark]" /></div> : <><h1 className="mt-4 text-3xl font-black sm:text-4xl">{release.name}</h1><p className="mt-3 flex items-center gap-2 text-slate-300"><CalendarDays size={18} />Due {new Date(`${release.due_date}T00:00:00`).toLocaleDateString(undefined, { dateStyle: "long" })}</p></>}</div><div className="flex gap-2">{canEditRelease && (editingRelease ? <><button onClick={saveRelease} className="inline-flex items-center gap-2 self-start rounded-lg bg-white/10 px-3 py-2 text-sm font-semibold hover:bg-white/20"><Save size={17} />Save</button><button aria-label="Cancel release edit" onClick={() => setEditingRelease(false)} className="rounded-lg p-2 hover:bg-white/10"><X size={17} /></button></> : <button onClick={() => setEditingRelease(true)} className="inline-flex items-center gap-2 self-start rounded-lg px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-white/10"><Pencil size={17} />Edit</button>)}{canDelete && <button onClick={remove} className="inline-flex items-center gap-2 self-start rounded-lg px-3 py-2 text-sm font-semibold text-red-300 hover:bg-white/10"><Trash2 size={17} />Delete</button>}</div></div><div className="mt-8 [&_span]:text-slate-300"><ProgressBar completed={release.completed_steps} total={release.total_steps} /></div></section>
    <section className="panel mt-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Release access</p><h2 className="section-title">Teammates</h2><p className="mt-1 text-sm text-slate-500">Only these people can open this release. Team membership alone grants no access.</p></div>{canManageCollaborators && <div className="flex flex-col gap-2 sm:flex-row"><input type="email" aria-label="Release teammate email" value={collaboratorEmail} onChange={(event) => setCollaboratorEmail(event.target.value)} placeholder="teammate@example.com" className="rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-700" /><select aria-label="Release teammate role" value={collaboratorRole} onChange={(event) => setCollaboratorRole(event.target.value as CollaboratorInput["role"])} className="rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-700"><option value="other">Other</option><option value="admin">Admin</option></select><button onClick={addCollaborator} disabled={!collaboratorEmail.trim()} className="btn-primary py-2"><UserPlus size={17} />Add</button></div>}</div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{collaborators.map((collaborator) => <div key={collaborator.user_id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="grid h-9 w-9 place-items-center rounded-full bg-brand/10 font-bold text-brand">{collaborator.full_name.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{collaborator.full_name}{collaborator.user_id === user?.id && " (you)"}</p><p className="truncate text-xs text-slate-500">{collaborator.email}</p></div>{collaborator.role === "owner" ? <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">Owner</span> : canManageCollaborators ? <><select aria-label={`Role for ${collaborator.email}`} value={collaborator.role} onChange={(event) => updateCollaborator(collaborator.user_id, event.target.value as CollaboratorInput["role"])} className="rounded border border-slate-200 bg-transparent px-2 py-1 text-xs capitalize dark:border-slate-700"><option value="other">Other</option><option value="admin">Admin</option></select>{collaborator.user_id !== user?.id && <button aria-label={`Remove ${collaborator.email}`} onClick={() => removeCollaborator(collaborator.user_id)} className="rounded p-1 text-red-500 hover:bg-red-50"><UserMinus size={16} /></button>}</> : <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold capitalize text-slate-700">{collaborator.role}</span>}</div>)}</div>
    </section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.7fr_.8fr]"><section className="panel"><div className="flex items-center justify-between"><div><p className="eyebrow">Release checklist</p><h2 className="section-title">Readiness steps</h2></div><div className="flex gap-2"><button onClick={() => setEditing((value) => !value)} className="btn-secondary px-3 py-2 text-sm">{editing ? "Done" : "Edit"}</button>{editing && <button onClick={addStep} className="btn-primary px-3 py-2 text-sm"><Plus size={16} />Add</button>}</div></div><div className="mt-5 divide-y divide-slate-100 dark:divide-slate-800">{Object.entries(release.steps).map(([name, done], index) => <div key={name} draggable={editing} onDragStart={() => setDragged(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(index)} className="flex items-center gap-3 py-4">{editing && <GripVertical className="cursor-grab text-slate-400" size={18} />}<input type="checkbox" checked={done} disabled={checklistMutation.isPending || editing} onChange={() => updateSteps({ ...release.steps, [name]: !done })} aria-label={name} className="h-5 w-5 accent-brand" />{editing ? <input aria-label={`Rename ${name}`} defaultValue={name} onBlur={(event) => rename(name, event.target.value)} className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-transparent px-2 py-1 font-semibold" /> : <span className={`flex-1 font-semibold ${done ? "text-slate-400 line-through" : ""}`}>{name}</span>}{editing && <button aria-label={`Delete ${name}`} disabled={Object.keys(release.steps).length === 1} onClick={() => removeStep(name)} className="rounded p-1 text-red-500 hover:bg-red-50"><Trash2 size={16} /></button>}</div>)}</div></section>
      <section className="panel self-start"><p className="eyebrow">Notes & context</p><h2 className="section-title">Additional information</h2><textarea value={info} onChange={(event) => setInfo(event.target.value)} disabled={!canEditRelease} rows={10} className="mt-5 w-full resize-y rounded-xl border border-slate-200 bg-transparent p-4 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/10 disabled:cursor-not-allowed disabled:bg-slate-50 dark:disabled:bg-slate-800" placeholder="Add rollout notes, links, owners…" />{canEditRelease ? <button disabled={info === (release.additional_info ?? "")} onClick={saveInfo} className="btn-primary mt-4 w-full"><Save size={18} />Save information</button> : <p className="mt-3 text-sm text-slate-500">Your role can update the checklist but cannot edit release notes.</p>}</section>
      <section className="panel self-start"><p className="eyebrow">Audit log</p><h2 className="section-title">Activity</h2><div className="mt-5 max-h-[520px] space-y-5 overflow-y-auto">{activitiesQuery.isLoading ? [1,2,3].map((item) => <div key={item} className="h-14 animate-pulse rounded-lg bg-slate-100" />) : activitiesQuery.data?.length ? activitiesQuery.data.map((activity) => <article key={activity.id} className="border-l-2 border-brand/30 pl-4"><time className="text-xs text-slate-400">{new Date(activity.created_at).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</time><p className="mt-1 text-sm"><strong>{activity.user_name}</strong> {activityCopy[activity.action] ?? activity.action.replaceAll("_", " ")} {typeof activity.metadata?.step === "string" && <q className="font-semibold">{activity.metadata.step}</q>}</p></article>) : <p className="text-sm text-slate-500">No activity yet.</p>}</div></section></div>
  </div></>;
}
