import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Crown, Plus, Shield, Trash2, UserMinus, Users } from "lucide-react";
import { useState } from "react";
import { teamApi } from "../api/teams";
import { useAuth } from "../contexts/AuthContext";
import type { Team, TeamRole } from "../types";

const roleStyle: Record<TeamRole, string> = { owner: "bg-amber-100 text-amber-800", admin: "bg-blue-100 text-blue-800", member: "bg-slate-100 text-slate-700" };

export function TeamsPage() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  const { data: teams = [], isLoading } = useQuery({ queryKey: ["teams"], queryFn: teamApi.list });
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = teams.find((team) => team.id === selectedId) ?? teams[0];
  const [teamName, setTeamName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState<TeamRole>("member"); const [message, setMessage] = useState("");
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["teams"] });
  const create = useMutation({ mutationFn: teamApi.create, onSuccess: async (team) => { setTeamName(""); setSelectedId(team.id); await refresh(); } });
  const invite = async () => { if (!selected || !email) return; const result = await teamApi.invite(selected.id, email, role); setEmail(""); setMessage(result.status === "member_added" ? "Member added" : "Invitation will be applied when they sign up"); await refresh(); };
  const remove = async (team: Team, userId: string) => { if (!window.confirm("Remove this member from the team?")) return; await teamApi.remove(team.id, userId); await refresh(); };
  const transfer = async (team: Team, userId: string) => { if (!window.confirm("Transfer team ownership? You will become an admin.")) return; await teamApi.transfer(team.id, userId); await refresh(); };
  const deleteTeam = async (team: Team) => { if (!window.confirm(`Delete “${team.name}” and its releases?`)) return; await teamApi.delete(team.id); setSelectedId(null); await refresh(); };
  if (isLoading) return <div className="mx-auto max-w-6xl p-6"><div className="h-72 animate-pulse rounded-2xl bg-white" /></div>;
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Collaboration</p><h1 className="section-title">Teams</h1><p className="mt-2 text-slate-500">Create shared workspaces, invite collaborators, and manage access.</p></div><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); if (teamName.trim()) create.mutate(teamName.trim()); }}><input aria-label="Team name" value={teamName} onChange={(event) => setTeamName(event.target.value)} placeholder="New team name" className="rounded-xl border border-slate-200 bg-white px-4 py-2 dark:border-slate-700 dark:bg-slate-900" /><button className="btn-primary py-2" disabled={create.isPending}><Plus size={18} />Create</button></form></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="panel self-start p-3">{teams.length ? teams.map((team) => <button key={team.id} onClick={() => setSelectedId(team.id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left ${selected?.id === team.id ? "bg-brand text-white" : "hover:bg-slate-50 dark:hover:bg-slate-800"}`}><Users size={18} /><span className="min-w-0 flex-1 truncate font-bold">{team.name}</span><span className="text-xs capitalize">{team.role}</span></button>) : <div className="p-8 text-center text-sm text-slate-500">No teams yet.</div>}</aside>
      {selected ? <section className="space-y-6"><div className="panel"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-black">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">{selected.members.length} member{selected.members.length === 1 ? "" : "s"}</p></div>{selected.role === "owner" && <button onClick={() => deleteTeam(selected)} className="rounded-lg p-2 text-red-500 hover:bg-red-50" aria-label="Delete team"><Trash2 /></button>}</div>
        {(selected.role === "owner" || selected.role === "admin") && <div className="mt-6 rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="font-bold">Invite member</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input aria-label="Invite email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@example.com" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-900" /><select aria-label="Invite role" value={role} onChange={(event) => setRole(event.target.value as TeamRole)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="member">Member</option><option value="admin">Admin</option></select><button onClick={invite} className="btn-primary py-2">Invite</button></div>{message && <p role="status" className="mt-2 text-sm text-brand">{message}</p>}</div>}
        <div className="mt-6 divide-y divide-slate-100 dark:divide-slate-800">{selected.members.map((member) => <div key={member.user_id} className="flex items-center gap-3 py-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-brand/10 font-bold text-brand">{member.full_name.charAt(0)}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{member.full_name}{member.user_id === user?.id && " (you)"}</p><p className="truncate text-sm text-slate-500">{member.email}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${roleStyle[member.role]}`}>{member.role === "owner" ? <Crown className="mr-1 inline" size={12} /> : member.role === "admin" ? <Shield className="mr-1 inline" size={12} /> : null}{member.role}</span>{selected.role === "owner" && member.role !== "owner" && <button title="Transfer ownership" onClick={() => transfer(selected, member.user_id)} className="rounded p-2 text-amber-600 hover:bg-amber-50"><Crown size={17} /></button>}{(selected.role === "owner" || selected.role === "admin") && member.role !== "owner" && member.user_id !== user?.id && <button title="Remove member" onClick={() => remove(selected, member.user_id)} className="rounded p-2 text-red-500 hover:bg-red-50"><UserMinus size={17} /></button>}</div>)}</div>
        {selected.invitations.length > 0 && <div className="mt-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Pending invitations</p>{selected.invitations.map((invitation) => <div key={invitation.id} className="mt-2 flex justify-between rounded-lg border border-dashed border-slate-200 p-3 text-sm"><span>{invitation.email}</span><span className="capitalize text-slate-500">{invitation.role}</span></div>)}</div>}</div></section> : <div className="state"><h2>Create your first team</h2><p>Shared releases, permissions, and invitations will appear here.</p></div>}
    </div>
  </div>;
}
